version: "2"
services:
  consul:
    image: consul
    environment:
      - "CONSUL_LOCAL_CONFIG={\"disable_update_check\": true}"
      - "CONSUL_BIND_INTERFACE=eth0"
      - "CONSUL_HTTP_ADDR=0.0.0.0"
    entrypoint:
      - consul
      - agent
      - -server
      - -bootstrap-expect=1
      - -data-dir=/consul/data
      - -node=consul-one
      - -bind={{ GetInterfaceIP "eth0" }}
      - -client=0.0.0.0
      - -enable-script-checks=true
      - -ui
    volumes:
      - ./config/consul:/consul/data
    ports:
      - "8500:8500"
      - "8600:8600"
    networks:
      spnet:
        ipv4_address: 172.30.0.9

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      spnet:

  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ###TODO ADD HOSTNAME HERE ### 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      spnet:
   
  backend:
    image: streampipes/backend:0.51.1
    depends_on:
      - "consul"
    ports:
      - "8030:8030"
    volumes:
      - ./config:/root/.streampipes
      - ./config/RDF4J:/root/.RDF4J
    networks:
      spnet:

  elasticsearch:
    image: streampipes/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./config/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      spnet:

  kibana:
    image: kibana:5.2.2
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana/kibana.yml:/opt/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      spnet:

  activemq:
    image: streampipes/activemq
    ports:
      - "61616:61616"
      - "61614:61614"
      - "8161:8161"
    networks:
      spnet:

  couchdb:
    image: couchdb:2.1.1
    ports:
      - "5984:5984"
    volumes:
      - ./config/couchdb/data:/opt/couchdb/data
    networks:
      spnet:

  jobmanager:
    image: streampipes/flink:1.4
    ports:
      - "8081:8099"
    command: jobmanager
    networks:
      spnet:

  taskmanager:
    image: streampipes/flink:1.4
    command: taskmanager
    environment:
      - FLINK_NUM_SLOTS=20
    networks:
      spnet:

  nginx:
    image: streampipes/ui:0.5.0
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      spnet:
  
  pe-examples-sources:
    image: streampipes/pe-examples-sources:0.51.1
    depends_on:
      - "consul"
    ports:
      - "8098:8090"
    networks:
      spnet:

  pe-examples-flink:
    image: streampipes/pe-examples-flink:0.51.2
    depends_on:
      - "consul"
    ports:
      - "8097:8090"
    networks:
      spnet:

  pe-examples-jvm:
    image: streampipes/pe-examples-jvm:0.51.1
    depends_on:
      - "consul"
    environment:
      - STREAMPIPES_HOST=###TODO ADD HOSTNAME HERE ###
    ports:
      - "8096:8090"
    networks:
      spnet:

networks:
  spnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.30.0.0/16
         gateway: 172.30.0.1

